// This file is @generated by prost-build.
/// All x402 settlements detected in a block
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Settlements {
    #[prost(message, repeated, tag = "1")]
    pub settlements: ::prost::alloc::vec::Vec<Settlement>,
    #[prost(uint64, tag = "2")]
    pub slot: u64,
    #[prost(message, optional, tag = "3")]
    pub block_timestamp: ::core::option::Option<::prost_types::Timestamp>,
}
/// A single x402 payment settlement on Solana
///
/// Detected via the SVM `exact` scheme (specs/schemes/exact/scheme_exact_svm.md):
/// 1. Facilitator sponsors a transaction with a partially-signed payload from the client
/// 2. Transaction contains ComputeBudget + SPL Token(-2022) TransferChecked + SPL Memo
/// 3. Fee payer (facilitator) is distinct from the TransferChecked authority (payer)
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Settlement {
    /// {signature}-{instruction_index}
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Base58 transaction signature
    #[prost(string, tag = "2")]
    pub signature: ::prost::alloc::string::String,
    /// Index of the TransferChecked within tx
    #[prost(uint32, tag = "3")]
    pub instruction_index: u32,
    #[prost(uint64, tag = "4")]
    pub slot: u64,
    #[prost(message, optional, tag = "5")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    /// Payment details
    ///
    /// Who paid (TransferChecked authority, base58)
    #[prost(string, tag = "6")]
    pub payer: ::prost::alloc::string::String,
    /// Resource server wallet (owner of destination ATA)
    #[prost(string, tag = "7")]
    pub recipient: ::prost::alloc::string::String,
    /// Destination associated token account
    #[prost(string, tag = "8")]
    pub destination_ata: ::prost::alloc::string::String,
    /// SPL token mint (e.g. USDC on Solana)
    #[prost(string, tag = "9")]
    pub mint: ::prost::alloc::string::String,
    /// Payment amount in atomic units
    #[prost(string, tag = "10")]
    pub amount: ::prost::alloc::string::String,
    /// Token decimals (from TransferChecked data)
    #[prost(uint32, tag = "11")]
    pub decimals: u32,
    /// Token program identification
    ///
    /// spl-token or token-2022
    #[prost(string, tag = "12")]
    pub token_program: ::prost::alloc::string::String,
    /// Facilitator (fee payer)
    ///
    /// Transaction fee payer, base58
    #[prost(string, tag = "13")]
    pub facilitator: ::prost::alloc::string::String,
    /// Transaction fee in lamports
    #[prost(string, tag = "14")]
    pub fee_lamports: ::prost::alloc::string::String,
    /// Payment reference
    ///
    /// Memo instruction data (UTF-8)
    #[prost(string, tag = "15")]
    pub memo: ::prost::alloc::string::String,
    /// Facilitator enrichment (from x402scan registry)
    ///
    /// e.g. "Coinbase", "PayAI" — empty if unknown
    #[prost(string, tag = "16")]
    pub facilitator_name: ::prost::alloc::string::String,
    /// true if fee_payer is in the known-facilitator allowlist
    #[prost(bool, tag = "17")]
    pub facilitator_known: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PayerStats {
    #[prost(message, repeated, tag = "1")]
    pub stats: ::prost::alloc::vec::Vec<PayerStat>,
    #[prost(uint64, tag = "2")]
    pub slot: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PayerStat {
    #[prost(string, tag = "1")]
    pub payer_address: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub total_spent: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub total_payments: u64,
    #[prost(message, optional, tag = "4")]
    pub first_payment_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "5")]
    pub last_payment_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecipientStats {
    #[prost(message, repeated, tag = "1")]
    pub stats: ::prost::alloc::vec::Vec<RecipientStat>,
    #[prost(uint64, tag = "2")]
    pub slot: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RecipientStat {
    #[prost(string, tag = "1")]
    pub recipient_address: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub total_received: ::prost::alloc::string::String,
    #[prost(uint64, tag = "3")]
    pub total_payments: u64,
    #[prost(message, optional, tag = "4")]
    pub first_payment_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "5")]
    pub last_payment_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FacilitatorStats {
    #[prost(message, repeated, tag = "1")]
    pub stats: ::prost::alloc::vec::Vec<FacilitatorStat>,
    #[prost(uint64, tag = "2")]
    pub slot: u64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FacilitatorStat {
    #[prost(string, tag = "1")]
    pub facilitator_address: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub total_settlements: u64,
    #[prost(string, tag = "3")]
    pub total_volume_settled: ::prost::alloc::string::String,
    /// Total lamports spent on tx fees
    #[prost(string, tag = "4")]
    pub total_fees_spent: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "5")]
    pub first_settlement_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "6")]
    pub last_settlement_at: ::core::option::Option<::prost_types::Timestamp>,
}
